alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: services.topick.fyi
  type: PRIMARY
ingress:
  rules:
  - component:
      name: topick
    match:
      path:
        prefix: /
name: topick
region: sfo
services:
- build_command: npm run build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: ExoKomodo/topick
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs
  name: topick
  run_command: npm run start
  source_dir: server
